// Generated by scripts/generate-gallery-images.js.
// Edit the image files in assets/pictures/, then rerun the generator.
window.HOB_GALLERY_IMAGES = [
  {
    "file": "balloon cluster Large.jpeg",
    "src": "assets/pictures/balloon%20cluster%20Large.jpeg",
    "caption": "balloon cluster Large"
  },
  {
    "file": "full arch Large.jpeg",
    "src": "assets/pictures/full%20arch%20Large.jpeg",
    "caption": "full arch Large"
  },
  {
    "file": "full arch with custom balloons Large.jpeg",
    "src": "assets/pictures/full%20arch%20with%20custom%20balloons%20Large.jpeg",
    "caption": "full arch with custom balloons Large"
  },
  {
    "file": "full cherry arch Large.jpeg",
    "src": "assets/pictures/full%20cherry%20arch%20Large.jpeg",
    "caption": "full cherry arch Large"
  },
  {
    "file": "half arch with dried flowers Large.jpeg",
    "src": "assets/pictures/half%20arch%20with%20dried%20flowers%20Large.jpeg",
    "caption": "half arch with dried flowers Large"
  },
  {
    "file": "half arch with floweres Large.jpeg",
    "src": "assets/pictures/half%20arch%20with%20floweres%20Large.jpeg",
    "caption": "half arch with floweres Large"
  },
  {
    "file": "half arch with flowers Large.jpeg",
    "src": "assets/pictures/half%20arch%20with%20flowers%20Large.jpeg",
    "caption": "half arch with flowers Large"
  },
  {
    "file": "half arch with stars Large.jpeg",
    "src": "assets/pictures/half%20arch%20with%20stars%20Large.jpeg",
    "caption": "half arch with stars Large"
  },
  {
    "file": "multicolour daisies Large.jpeg",
    "src": "assets/pictures/multicolour%20daisies%20Large.jpeg",
    "caption": "multicolour daisies Large"
  },
  {
    "file": "orange daisy Large.jpeg",
    "src": "assets/pictures/orange%20daisy%20Large.jpeg",
    "caption": "orange daisy Large"
  },
  {
    "file": "pink daisy Large.jpeg",
    "src": "assets/pictures/pink%20daisy%20Large.jpeg",
    "caption": "pink daisy Large"
  },
  {
    "file": "single flower Large.jpeg",
    "src": "assets/pictures/single%20flower%20Large.jpeg",
    "caption": "single flower Large"
  },
  {
    "file": "turquois daisy Large.jpeg",
    "src": "assets/pictures/turquois%20daisy%20Large.jpeg",
    "caption": "turquois daisy Large"
  }
];
